### ISSUE TITLE
pyrelic/_relic.pxd and pyrelic/_relic.pyi can be removed?

### ISSUE THREAD

**Issue by duanbing** [sebastinas/pyrelic#1]
Hi, When I build this repo after I deleted pxd and pyi, it works too.  is it true?

**Comment by duanbing** [comment]
@sebastinas

**Comment by sebastinas** [comment]
They cannot be removed. `pyrelic/_relic.pxd` is required to produce `pyrelic/_relic.c`. So if the C code needs to be regenerated, cython won't be able to do that without the pxd file. `pyrelic/_relic.pyi` is consumed by type checkers such as mypy. If you don't care about type annotations, then you can remove it.
