### ISSUE TITLE
Issue about the curve parameters

### ISSUE THREAD

**Issue by Vageous** [sebastinas/pyrelic#6]
Dear Sebastian,
I'm new to the pyrelic. I have a problem with the group G1, G2, and GT.  How can I choose the pairing-friendly curve parameters, like the "BLS12-455" and other curves?

**Comment by sebastinas** [comment]
You can't. You get whichever curve your relic installation has enabled.

**Comment by Vageous** [comment]
Thanks for your quick response. I get it.
