### ISSUE TITLE
Problem while installing python-relic via pip

### ISSUE THREAD

**Issue by Loryerba** [sebastinas/pyrelic#9]
I tried to install python-relic with this command "pip install python-relic" on VSCode with Python 3.12 and latest version of pip but 
I encountered this error: "It's not possibile to open the inclusion file: 'relic/relic_core.h': No such file or directory",
"Could not build wheels for python-relic, which is required to install pyproject.toml-based projects".

What can I do?

Thanks a lot ;)

**Comment by Loryerba** [comment]
@sebastinas

**Comment by Loryerba** [comment]
Thank you, but on the  https://github.com/relic-toolkit/relic in the wiki session, they suggest to run CMake with this command:
cmake ../relic-<version> but idk where download relic library to run this command.

**Comment by Loryerba** [comment]
Ok thank you, i've just found the latest release but I still have problem with build and install relic, i get 
make: *** "No rule to make target ';'. Stop.

**Comment by sebastinas** [comment]
That's probably best discussed with @dfaranha or somebody else from the relic project.

**Comment by Loryerba** [comment]
@sebastinas

**Comment by sebastinas** [comment]
Most of the functions and types have docstrings and there are some examples in the `examples` folder.

**Comment by Loryerba** [comment]
Solved by using WSL
